### ISSUE TITLE
Fix the template errors found in the logs

### ISSUE THREAD

**Issue by MansoorMajeed** [IEEEKeralaSection/rescuekerala#925]
There are lots of exceptions with template rendering. These are the logs

```
2018-08-24T09:52:44.585124+00:00 app[web.1]: DEBUG:django.template:Exception while resolving variable 'show' in template 'admin/change_list.html'.
2018-08-24T09:52:44.585126+00:00 app[web.1]: Traceback (most recent call last):
2018-08-24T09:52:44.585127+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 829, in _resolve_lookup
2018-08-24T09:52:44.585128+00:00 app[web.1]:     current = current[bit]
2018-08-24T09:52:44.585129+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/context.py", line 83, in __getitem__
2018-08-24T09:52:44.585131+00:00 app[web.1]:     raise KeyError(key)
2018-08-24T09:52:44.585132+00:00 app[web.1]: KeyError: 'show'
2018-08-24T09:52:44.585133+00:00 app[web.1]: 
2018-08-24T09:52:44.585135+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2018-08-24T09:52:44.585136+00:00 app[web.1]: 
2018-08-24T09:52:44.585137+00:00 app[web.1]: Traceback (most recent call last):
2018-08-24T09:52:44.585138+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 835, in _resolve_lookup
2018-08-24T09:52:44.585139+00:00 app[web.1]:     if isinstance(current, BaseContext) and getattr(type(current), bit):
2018-08-24T09:52:44.585141+00:00 app[web.1]: AttributeError: type object 'RequestContext' has no attribute 'show'
2018-08-24T09:52:44.585142+00:00 app[web.1]: 
2018-08-24T09:52:44.585143+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2018-08-24T09:52:44.585144+00:00 app[web.1]: 
2018-08-24T09:52:44.585145+00:00 app[web.1]: Traceback (most recent call last):
2018-08-24T09:52:44.585146+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 843, in _resolve_lookup
2018-08-24T09:52:44.585148+00:00 app[web.1]:     current = current[int(bit)]
2018-08-24T09:52:44.585149+00:00 app[web.1]: ValueError: invalid literal for int() with base 10: 'show'
2018-08-24T09:52:44.585150+00:00 app[web.1]: 
```

Please take a look

**Comment by ja8zyjits** [comment]
@MansoorMajeed they are just debug INFO not critical errors, generally you dont see them in production, they are for the development purposes only.

**Comment by ja8zyjits** [comment]
a fix would be to change `DEBUG` --> `INFO` in production in `floodrelief/settings.py` 
```python
'loggers': {
        'django': {
            'handlers':['file'],
            'propagate': True,
            'level':'DEBUG',
        },
        'MYAPP': {
            'handlers': ['file'],
            'level': 'DEBUG',
        },
    }
```

**Comment by vigneshhari** [comment]
The errors were caused due to a large number of elements in dropdowns , the issue is known and the fix is being implemented
